local mt = Emitters['E008']
mt.BulletArt = "Abilities\\Weapons\\WingedSerpentMissile\\WingedSerpentMissile.mdl"
mt.EmitTimes = 30
mt.InitialVeloc = 20
mt.Acc = -20
mt.AccDuration = 2
mt.EmitInterval = 0.05
mt.Cooldown = 2
mt.EmitterRotSpd = 150
mt.EmitNumPerShot = 3
mt.DistributionAngle = 120