local mt = Emitters['倒勾']
mt.BulletArt = "Abilities\\Weapons\\WingedSerpentMissile\\WingedSerpentMissile.mdl"
mt.EmitTimes = 1
mt.InitialVeloc = 15
mt.Acc = -12
mt.AccDuration = 2
mt.BulletRotSpd = 250
mt.EmitInterval = 1
mt.Cooldown = 2
mt.EmitNumPerShot = 3
mt.DistributionAngle = 15